// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RittalTravel.Data;

#nullable disable

namespace RittalTravel.Migrations
{
    [DbContext(typeof(RittalTravelContext))]
    partial class RittalTravelContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RittalTravel.Models.Organisation", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("ContactEmail").HasColumnType("nvarchar(max)");
                b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.ToTable("Organisations");
                b.HasData(new { Id = 1, ContactEmail = "admin@rittal.co.uk", Name = "Rittal UK" });
            });

            modelBuilder.Entity("RittalTravel.Models.Receipt", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<string>("Destination").HasColumnType("nvarchar(max)");
                b.Property<string>("FileName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<string>("Origin").HasColumnType("nvarchar(max)");
                b.Property<int>("OrganisationId").HasColumnType("int");
                b.Property<string>("OriginalFileName").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("TransportMode").HasColumnType("nvarchar(max)");
                b.Property<string>("TravellerName").HasColumnType("nvarchar(max)");
                b.Property<string>("TripDate").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("UploadedAt").HasColumnType("datetime2");
                b.HasKey("Id");
                b.ToTable("Receipts");
            });

            modelBuilder.Entity("RittalTravel.Models.Trip", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("int");
                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                b.Property<string>("DefraFactorYear").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Destination").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("DistanceKm").HasColumnType("float");
                b.Property<string>("DistanceMethodology").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("EmissionFactor").HasColumnType("float");
                b.Property<string>("Formula").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<double>("KgCO2e").HasColumnType("float");
                b.Property<string>("LoggedBy").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<string>("Notes").HasColumnType("nvarchar(max)");
                b.Property<string>("Origin").IsRequired().HasColumnType("nvarchar(max)");
                b.Property<int>("OrganisationId").HasColumnType("int");
                b.Property<int>("Passengers").HasColumnType("int");
                b.Property<string>("Purpose").HasColumnType("nvarchar(max)");
                b.Property<string>("ReceiptFileName").HasColumnType("nvarchar(max)");
                b.Property<DateTime>("TripDate").HasColumnType("datetime2");
                b.Property<string>("TravelClass").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("TravellerName").IsRequired().HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("TransportMode").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Waypoints").HasColumnType("nvarchar(max)");
                b.HasKey("Id");
                b.HasIndex("OrganisationId");
                b.ToTable("Trips");
            });

            modelBuilder.Entity("RittalTravel.Models.Trip", b =>
            {
                b.HasOne("RittalTravel.Models.Organisation", "Organisation").WithMany().HasForeignKey("OrganisationId").OnDelete(DeleteBehavior.Cascade).IsRequired();
                b.Navigation("Organisation");
            });
#pragma warning restore 612, 618
        }
    }
}
